name: Fetch Repository Variables

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Repository Variables
        id: fetch_vars
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.actions.listRepoVariables({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Log the response for debugging
            console.log('API Response:', response.data);

            // Check if variables exist and create .env content
            if (response.data.variables && response.data.variables.length > 0) {
              const envContent = response.data.variables
                .map(variable => `${variable.name}=${variable.value}`)
                .join('\n');

              // Write to .env file
              const fs = require('fs');
              fs.writeFileSync('./.env', envContent);
              console.log('.env file created successfully with repository variables.');
            } else {
              console.log('No repository variables found.');
            }

      - name: Upload .env file
        uses: actions/upload-artifact@v2
        with:
          name: env-file
          path: .env
